// <auto-generated />
using System;
using BMReleaseManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BMReleaseManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BMReleaseManager.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Changes")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("BMReleaseManager.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirmwareReleaseNote")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("BMReleaseManager.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BMReleaseManager.Models.HistoryNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VersionHistoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VersionHistoryId");

                    b.ToTable("HistoryNotes");
                });

            modelBuilder.Entity("BMReleaseManager.Models.HistoryNoteCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("HistoryNoteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("HistoryNoteId", "CustomerId")
                        .IsUnique();

                    b.ToTable("HistoryNoteCustomers");
                });

            modelBuilder.Entity("BMReleaseManager.Models.Software", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileLocation")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ReleaseMethod")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiresCustomerValidation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Softwares");
                });

            modelBuilder.Entity("BMReleaseManager.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BMReleaseManager.Models.VersionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("PreReleaseById")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PreReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ProductionReadyById")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ProductionReadyDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReleaseStatus")
                        .HasColumnType("integer");

                    b.Property<int>("ReleasedById")
                        .HasColumnType("integer");

                    b.Property<int?>("ReleasedStatusById")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReleasedStatusDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PreReleaseById");

                    b.HasIndex("ProductionReadyById");

                    b.HasIndex("ReleasedById");

                    b.HasIndex("ReleasedStatusById");

                    b.HasIndex("SoftwareId");

                    b.HasIndex("Version", "SoftwareId")
                        .IsUnique();

                    b.ToTable("VersionHistories");
                });

            modelBuilder.Entity("BMReleaseManager.Models.VersionHistoryCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("VersionHistoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("VersionHistoryId", "CustomerId")
                        .IsUnique();

                    b.ToTable("VersionHistoryCustomers");
                });

            modelBuilder.Entity("BMReleaseManager.Models.AuditLog", b =>
                {
                    b.HasOne("BMReleaseManager.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("BMReleaseManager.Models.Customer", b =>
                {
                    b.HasOne("BMReleaseManager.Models.Country", "Country")
                        .WithMany("Customers")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("BMReleaseManager.Models.HistoryNote", b =>
                {
                    b.HasOne("BMReleaseManager.Models.VersionHistory", "VersionHistory")
                        .WithMany("HistoryNotes")
                        .HasForeignKey("VersionHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VersionHistory");
                });

            modelBuilder.Entity("BMReleaseManager.Models.HistoryNoteCustomer", b =>
                {
                    b.HasOne("BMReleaseManager.Models.Customer", "Customer")
                        .WithMany("HistoryNoteCustomers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BMReleaseManager.Models.HistoryNote", "HistoryNote")
                        .WithMany("HistoryNoteCustomers")
                        .HasForeignKey("HistoryNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("HistoryNote");
                });

            modelBuilder.Entity("BMReleaseManager.Models.VersionHistory", b =>
                {
                    b.HasOne("BMReleaseManager.Models.User", "PreReleaseBy")
                        .WithMany()
                        .HasForeignKey("PreReleaseById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BMReleaseManager.Models.User", "ProductionReadyBy")
                        .WithMany()
                        .HasForeignKey("ProductionReadyById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BMReleaseManager.Models.User", "ReleasedBy")
                        .WithMany("VersionHistories")
                        .HasForeignKey("ReleasedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BMReleaseManager.Models.User", "ReleasedStatusBy")
                        .WithMany()
                        .HasForeignKey("ReleasedStatusById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BMReleaseManager.Models.Software", "Software")
                        .WithMany("VersionHistories")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PreReleaseBy");

                    b.Navigation("ProductionReadyBy");

                    b.Navigation("ReleasedBy");

                    b.Navigation("ReleasedStatusBy");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("BMReleaseManager.Models.VersionHistoryCustomer", b =>
                {
                    b.HasOne("BMReleaseManager.Models.Customer", "Customer")
                        .WithMany("VersionHistoryCustomers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BMReleaseManager.Models.VersionHistory", "VersionHistory")
                        .WithMany("VersionHistoryCustomers")
                        .HasForeignKey("VersionHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("VersionHistory");
                });

            modelBuilder.Entity("BMReleaseManager.Models.Country", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("BMReleaseManager.Models.Customer", b =>
                {
                    b.Navigation("HistoryNoteCustomers");

                    b.Navigation("VersionHistoryCustomers");
                });

            modelBuilder.Entity("BMReleaseManager.Models.HistoryNote", b =>
                {
                    b.Navigation("HistoryNoteCustomers");
                });

            modelBuilder.Entity("BMReleaseManager.Models.Software", b =>
                {
                    b.Navigation("VersionHistories");
                });

            modelBuilder.Entity("BMReleaseManager.Models.User", b =>
                {
                    b.Navigation("VersionHistories");
                });

            modelBuilder.Entity("BMReleaseManager.Models.VersionHistory", b =>
                {
                    b.Navigation("HistoryNotes");

                    b.Navigation("VersionHistoryCustomers");
                });
#pragma warning restore 612, 618
        }
    }
}
